FROM docker.io/library/rust:1.88-alpine3.22
RUN apk add --no-cache musl-dev openssl-dev
ENV RUSTFLAGS=-Ctarget-feature=-crt-static

# Without this, linking fails.
# https://github.com/rust-lang/rust/issues/115450#issuecomment-1717228111
ENV OPENSSL_DIR=/usr

RUN rustup component add clippy
