FROM docker.io/rust:1.83-alpine3.20
RUN apk add --no-cache musl-dev openssl-dev
ENV RUSTFLAGS=-Ctarget-feature=-crt-static

# Without this, linking fails.
# https://github.com/rust-lang/rust/issues/115450#issuecomment-1717228111
ENV OPENSSL_DIR=/usr

RUN rustup component add clippy
