autofix:
	npm run format

build:
	npm run build

clean:
	rm -rf node_modules

lint:
	npm run lint

serve:
	VITE_API_ROOT=https://yerevan.treemaps.app/v1/ npm run dev

test:
	npm run test:unit -- run

.PHONY: build
