# This file runs the production environment on a virtual server.


name: trees

services:
  backend:
    image: ghcr.io/umonkey/treemap:latest
    container_name: backend
    hostname: treemap-backend
    command: /app/startup.sh
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - var:/app/var
    environment:
      - RUST_LOG=info
      - TREEMAP_CONFIG=/app/config.toml
    secrets:
      - aws_key
      - aws_region
      - aws_secret
      - files_key
      - files_secret
      - from_email
      - jwt_secret
      - osm_token
      - smtp_host
      - smtp_secret
      - smtp_user
      - sqs_key
      - sqs_secret
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  chatbot:
    image: ghcr.io/umonkey/treemap-chatbot:latest
    container_name: chatbot
    restart: unless-stopped
    volumes:
      - var:/app/var
    environment:
      - CHATBOT_DATABASE=/app/var/database.sqlite
      - FILES_BUCKET=${FILES_BUCKET}
      - FILES_REGION=${FILES_REGION}
      - FILES_ENDPOINT=${FILES_ENDPOINT}
      - RUST_LOG=info
    secrets:
      - files_key
      - files_secret
      - chatbot_token
    depends_on:
      - backend

  caddy:
    image: ghcr.io/umonkey/treemap-caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    depends_on:
      - backend
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  var:
  caddy_data:
  caddy_config:

secrets:
  aws_key:
    file: .secrets/aws_key.txt
  aws_secret:
    file: .secrets/aws_secret.txt
  aws_region:
    file: .secrets/aws_region.txt
  chatbot_token:
    file: .secrets/chatbot_token.txt
  files_key:
    file: .secrets/files_key.txt
  files_secret:
    file: .secrets/files_secret.txt
  jwt_secret:
    file: .secrets/jwt_secret.txt
  sqs_key:
    file: .secrets/sqs_key.txt
  sqs_secret:
    file: .secrets/sqs_secret.txt
  osm_token:
    file: .secrets/osm_token.txt
  smtp_user:
    file: .secrets/smtp_user.txt
  smtp_secret:
    file: .secrets/smtp_secret.txt
  smtp_host:
    file: .secrets/smtp_host.txt
  from_email:
    file: .secrets/from_email.txt
