# Trees of Yerevan startup file.
#
# This file starts both frontend and backend to run the Trees of Yerevan
# application in a dev environment.
#
# The web UI is available at:

name: trees_dev

services:

  backend:
    build:
      context: backend
    container_name: trees_backend
    command: /app/startup.sh
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - var:/app/var
    environment:
      - FILES_KEY=${FILES_KEY}
      - FILES_SECRET=${FILES_SECRET}
      - JWT_SECRET=foobar
      - RUST_LOG=info,treemap=debug
      - SQS_KEY=${SQS_KEY}
      - SQS_SECRET=${SQS_SECRET}
      - TREEMAP_CONFIG=/app/config.toml.dev
      - TURSO_TOKEN

  frontend:
    build:
      context: frontend
    container_name: trees_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/.svelte-kit
    depends_on:
      - backend

volumes:
  var:
