# Trees of Yerevan startup file.
#
# This file starts both frontend and backend to run the Trees of Yerevan
# application in a dev environment.
#
# The web UI is available at:

name: trees_dev

services:

  postgres:
    image: postgres:16
    container_name: trees_postgres
    environment:
      POSTGRES_DB: treemap
      POSTGRES_USER: treemap
      POSTGRES_PASSWORD: treemap_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: services/backend
    container_name: trees_backend
    dns:
      - 8.8.8.8
    command: /app/startup.sh
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - var:/app/var
    depends_on:
      - postgres
    environment:
      - FILES_KEY=${FILES_KEY}
      - FILES_SECRET=${FILES_SECRET}
      - JWT_SECRET=foobar
      - RUST_LOG=info,treemap=info
      - SQS_KEY=
      - SQS_SECRET=
      - TREEMAP_CONFIG=/app/config.toml.dev

  frontend:
    build:
      context: services/frontend
    container_name: trees_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
      - svelte_kit_data:/app/.svelte-kit
    depends_on:
      - backend

volumes:
  var:
  svelte_kit_data:
  postgres_data:
