# Trees of Yerevan startup file.
#
# This file starts both frontend and backend to run the Trees of Yerevan
# application in a dev environment.
#
# The web UI is available at:

name: trees_dev

services:
  backend:
    build:
      context: services/backend
    container_name: trees_backend
    dns:
      - 8.8.8.8
    command: /app/startup.sh
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - var:/app/var
    environment:
      - RUST_LOG=info,treemap=debug
      - TREEMAP_CONFIG=/app/config.toml.dev
    secrets:
      - files_key
      - files_secret
      - jwt_secret
      - mapillary_org_id
      - mapillary_token
      - sqs_key
      - sqs_secret
      - osm_token

  frontend:
    build:
      context: services/frontend
    container_name: trees_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./services/frontend:/app
      - svelte_kit_data:/app/.svelte-kit
    depends_on:
      - backend

volumes:
  var:
  svelte_kit_data:

secrets:
  chatbot_token:
    file: .secrets/chatbot_token.txt
  files_key:
    file: .secrets/files_key.txt
  files_secret:
    file: .secrets/files_secret.txt
  jwt_secret:
    file: .secrets/jwt_secret.txt
  mapillary_org_id:
    file: .secrets/mapillary_org_id.txt
  mapillary_token:
    file: .secrets/mapillary_token.txt
  sqs_key:
    file: .secrets/sqs_key.txt
  sqs_secret:
    file: .secrets/sqs_secret.txt
  osm_token:
    file: .secrets/osm_token.txt
