# Deploy *Trees of Yerevan* to Fly.io
#
# The application is packaged as a single Docker container, which runs both frontend and backend.
#
# Some hints:
# - Use `fly logs` to view the logs of your application.
# - Use `fly ssh console` to access the machine running your application.
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'treemap-blue-frog-3927'
primary_region = 'waw'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  method = 'GET'
  path = '/v1/trees/stats'
  timeout = '1s'
  interval = '1m0s'
  grace_period = '10s'

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source = "treemaps_var"
  destination = "/app/var"
