# fly.toml app configuration file generated for treemap-blue-frog-3927 on 2025-07-21T14:39:28+04:00
#
# Please note that this deployment uses a pre-built container image created on previous CI/CD steps.
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'treemap-blue-frog-3927'
primary_region = 'waw'

[build]
  image = "ghcr.io/umonkey/treemap:latest"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  method = 'GET'
  path = '/v1/trees/stats'
  timeout = '1s'
  interval = '1m0s'
  grace_period = '10s'

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source = "treemaps_var"
  destination = "/app/var"
