[program:chatbot]
command = /app/bin/chatbot
directory = /app
autostart = true
autorestart = true
startsecs = 1
startretries = 1000
restartpause = 5
user = root

; Redirect logs to stdout/stderr
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
