DELETE FROM species;
INSERT INTO species (name, local, keywords) VALUES ('Acer negundo', 'Box Elder', 'клён;ясенелистный;boxelder;maple;ashleaf;manitoba');
INSERT INTO species (name, local, keywords) VALUES ('Acer pseudoplatanus', 'Sycamore maple', 'клён белый;явор;немецкий;maple;sycamore');
INSERT INTO species (name, local, keywords) VALUES ('Acer', 'Maple', 'клён');
INSERT INTO species (name, local, keywords) VALUES ('Aesculus hippocastanum', 'Horse chestnut', 'каштан;конский;buckeye;conker');
INSERT INTO species (name, local, keywords) VALUES ('Betula', 'Birch', 'берёза;береза');
INSERT INTO species (name, local, keywords) VALUES ('Catalpa', 'Catalpa', 'катальпа');
INSERT INTO species (name, local, keywords) VALUES ('Cercis siliquastrum', 'Judas tree', 'багряник европейский');
INSERT INTO species (name, local, keywords) VALUES ('Fraxinus', 'Ash', 'ясень');
INSERT INTO species (name, local, keywords) VALUES ('Juglans', 'Walnut', 'орех');
INSERT INTO species (name, local, keywords) VALUES ('Morus', 'Mulberry', 'шелковица;silkworm');
INSERT INTO species (name, local, keywords) VALUES ('Paulwnia', 'Foxglove', 'пауловния;павловния');
INSERT INTO species (name, local, keywords) VALUES ('Picea', 'Spruce', 'ель;ёлка');
INSERT INTO species (name, local, keywords) VALUES ('Pinus', 'Pine', 'сосна');
INSERT INTO species (name, local, keywords) VALUES ('Platanus orientalis', 'Oriental plane', 'sycamore;платан;чинар');
INSERT INTO species (name, local, keywords) VALUES ('Populus alba', 'White poplar', 'тополь;белый');
INSERT INTO species (name, local, keywords) VALUES ('Populus', 'Poplar', 'тополь');
INSERT INTO species (name, local, keywords) VALUES ('Quercus robur', 'Pedunculate oak', 'дуб;черешчатый');
INSERT INTO species (name, local, keywords) VALUES ('Quercus rubra', 'Northern red oak', 'дуб;красный');
INSERT INTO species (name, local, keywords) VALUES ('Quercus', 'Oak', 'дуб');
INSERT INTO species (name, local, keywords) VALUES ('Salix', 'Willow', 'ива');
INSERT INTO species (name, local, keywords) VALUES ('Thuja', 'Cedar', 'туя;биота;cedar');
INSERT INTO species (name, local, keywords) VALUES ('Tilia', 'Linden', 'липа');
INSERT INTO species (name, local, keywords) VALUES ('Ulmus glabra', 'Wych elm', 'вяз;шершавый;scots');
INSERT INTO species (name, local, keywords) VALUES ('Ulmus parvifolia', 'Lacebark elm', 'вяз;мелколистный;карагач;chinese;sieboldii');
INSERT INTO species (name, local, keywords) VALUES ('Ulmus', 'Elm', 'вяз;карагач');
