DELETE FROM species;
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Acer negundo', 'Box Elder', 'клён;ясенелистный;boxelder;maple;ashleaf;manitoba', 'Q161166');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Acer pseudoplatanus', 'Sycamore maple', 'клён белый;явор;немецкий;maple;sycamore', 'Q156944');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Acer', 'Maple', 'клён', 'Q42292');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Aesculus hippocastanum', 'Horse chestnut', 'каштан;конский;buckeye;conker', 'Q26899');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Ailanthus altissima', 'Tree of heaven', 'айлант;высочайший', 'Q159570');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Betula', 'Birch', 'берёза;береза', 'Q25243');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Catalpa', 'Catalpa', 'катальпа', 'Q158072');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Cercis siliquastrum', 'Judas tree', 'багряник европейский', 'Q29488');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Cercis', 'Cercis', 'багряник', 'Q29033');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Ficus carica', 'Fig', 'инжир;фиг', 'Q36146');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Fraxinus', 'Ash', 'ясень', 'Q128887');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Juglans regia', 'Common walnut', 'орех;грецкий;fallax', 'Q46871');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Juglans', 'Walnut', 'орех', 'Q2453469');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Juniperus virginiana', 'Red cedar', 'можжевельник;виргинский', 'Q157522');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Maclur pomifera', 'Osage orange', 'маклюра;адамово яблоко', 'Q1066106');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Morus alba', 'White mulberry', 'шелковица;silkworm;белая', 'Q157307');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Morus nigra', 'Black mulberry', 'шелковица;silkworm;чёрная;черная', 'Q161040');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Morus', 'Mulberry', 'шелковица;silkworm', 'Q44789');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Paulownia', 'Foxglove', 'пауловния;павловния', 'Q165173');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Philadelphus', 'Mock-orange', 'чубушник;жасмин', 'Q107394');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Picea pungens', 'Spruce', 'ель;ёлка;голубая', 'Q146025');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Picea', 'Spruce', 'ель;ёлка', 'Q26782');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Pinus', 'Pine', 'сосна', 'Q12024');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Platanus orientalis', 'Oriental plane', 'sycamore;платан;чинар', 'Q161105');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Platycladus orientalis', 'Chinese thuja', 'туя;биота;cedar;thuja', 'Q33482');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Populus alba', 'White poplar', 'тополь;белый;silver', 'Q146269');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Populus', 'Poplar', 'тополь;aspen', 'Q25356');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Prunus armeniaca', 'Apricot', 'абрикос', 'Q37453');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Prunus avium', 'Sweet cherry', 'черешня', 'Q165137');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Prunus cerasifera', 'Cherry plum', 'алыча', 'Q146951');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Prunus cerasus', 'Sour cherry', 'вишня', 'Q131517');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Prunus domestica', 'Plum tree', 'слива', 'Q44120');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Prunus persica', 'Peach', 'персик;нектарин', 'Q13189');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Prunus serrulata', 'Sakura', 'сакура;cherry blossom', 'Q871991');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Quercus robur', 'Pedunculate oak', 'дуб;черешчатый', 'Q165145');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Quercus rubra', 'Northern red oak', 'дуб;красный', 'Q147525');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Quercus', 'Oak', 'дуб', 'Q12004');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Robinia pseudoacacia', 'Locust', 'акация;белая;acacia', 'Q157417');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Salix', 'Willow', 'ива;sallow;osier', 'Q36050');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Sorbus aucuparia', 'Rowan', 'рябина', 'Q146198');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Styphnolobium japonicum', 'Japanese pagoda tree', 'софора японская;', 'Q288558');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Syringa', 'Lilac', 'сирень', 'Q157449');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Thuja occidentalis', 'Northern white cedar', 'туя;cedar', 'Q147468');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Thuja', 'Cedar', 'туя;биота;cedar', 'Q147255');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Tilia', 'Linden', 'липа;basswood;lime', 'Q127849');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Ulmus glabra', 'Wych elm', 'вяз;шершавый;scots', 'Q147498');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Ulmus parvifolia', 'Lacebark elm', 'вяз;мелколистный;карагач;chinese;sieboldii', 'Q1074099');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Ulmus', 'Elm', 'вяз;карагач', 'Q131113');
INSERT INTO species (name, local, keywords, wikidata_id) VALUES ('Vitis vinifera', 'Grape', 'виноград', 'Q30046');
