import {
	PUBLIC_API_ROOT,
	PUBLIC_AUTH_CLIENT_ID,
	PUBLIC_ENVIRONMENT,
	PUBLIC_FILE_BASE_URL,
	PUBLIC_GTM_ID,
	PUBLIC_MAPS_KEY,
	PUBLIC_MAPTILER_KEY,
	PUBLIC_OSM_AUTH_CLIENT_ID
} from '$env/static/public';

export const config = {
	apiRoot: PUBLIC_API_ROOT,
	fileBaseUrl: PUBLIC_FILE_BASE_URL,
	authClientId: PUBLIC_AUTH_CLIENT_ID,
	authCallback: `${PUBLIC_API_ROOT}v3/login/google`,
	gtmId: PUBLIC_GTM_ID,
	environment: PUBLIC_ENVIRONMENT,
	osmAuthClientId: PUBLIC_OSM_AUTH_CLIENT_ID,
	mapsKey: PUBLIC_MAPS_KEY,
	mapTilerKey: PUBLIC_MAPTILER_KEY
};
