name: deploy-v2

on:
  push:
    branches:
      - tree-page-2

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Cache temporary folders
      uses: actions/cache@v4
      with:
        path: |
          frontend-v2/node_modules
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Build the site
      run: make -C frontend-v2 install build

    - name: Clone pages
      uses: actions/checkout@v4
      with:
        repository: umonkey/umonkey.github.io
        path: v2

    - name: Update pages
      run: |
        git config --global user.email "hex@umonkey.net"
        git config --global user.name "GitHub Actions"
        rm -rf v2/*
        cp -R frontend-v2/build/* v2/
        cd v2
        git add .
        git commit -m "Deploy frontend-v2 to GitHub Pages"
        git push
      env:
        GH_TOKEN: ${{ github.token }}
