name: rust-test

on:
  push:
    branches-ignore:
      - master
    paths: 'backend/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
