name: "Frontend tests"

on:
  pull_request:
    paths: 'services/frontend/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Linter"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/frontend

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: services/frontend/package-lock.json

    - name: Enable Corepack
      run: corepack enable

    - name: Install new dependencies
      run: npm ci

    - name: Run tests
      run: make lint

  unit:
    name: "Unit tests"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/frontend

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: services/frontend/package-lock.json

    - name: Enable Corepack
      run: corepack enable

    - name: Install new dependencies
      run: npm ci

    - name: Run unit tests
      run: make test

